# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: Nightly
on:
  schedule:
    - cron: "00 04 * * *"

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the nightly (for SiVal job only)'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  VIVADO_VERSION: "2021.1"

jobs:
  fpga_cw310_sival_nightly:
    name: FPGA CW310 SiVal tests
    runs-on: [ubuntu-22.04-fpga, cw310]

    env:
      GS_PATH: gs://opentitan-test-results
      BAZEL_TEST_RESULTS: test_results.xml

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for the bitstream cache to work.
          ref: ${{ inputs.branch || 'earlgrey_1.0.0' }} # Schedule only work on the default branch, but we want to run on a different branch.

      - name: Install dependencies
        uses: ./.github/actions/prepare-env
        with:
          service_account_json: '${{ secrets.BAZEL_CACHE_CREDS }}'

      - uses: google-github-actions/setup-gcloud@v2

      - name: Run tests after ROM_EXT boot stage
        if: success() || failure()
        run: |
          module load xilinx/vivado
          bazel_tests="$(mktemp)"
          ./bazelisk.sh query 'attr("tags", "[\[ ]cw310_sival_rom_ext[,\]]", tests(//sw/device/...))' \
                                                    | grep usbdev\
                                                    > "$bazel_tests"
          cat $bazel_tests
          ./bazelisk.sh test --build_tests_only --target_pattern_file="$bazel_tests"


